services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    env_file:
      - ./api/.env
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - api
    env_file:
      - ./web/.env
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./api/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: