services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./api/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: