version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage: { }